In [1]:
import pandas as pd

In [10]:
df_clientes = pd.read_csv(r"C:\Users\User\OneDrive\Área de Trabalho\udemyPython\EDA\DADOS\churn_customers.csv")

In [11]:
df_clientes

      customerID  gender  SeniorCitizen Partner Dependents
0     7590-VHVEG  Female              0     Yes         No
1     5575-GNVDE    Male              0      No         No
2     3668-QPYBK    Male              0      No         No
3     7795-CFOCW    Male              0      No         No
4     9237-HQITU  Female              0      No         No
...          ...     ...            ...     ...        ...
7038  6840-RESVB    Male              0     Yes        Yes
7039  2234-XADUH  Female              0     Yes        Yes
7040  4801-JZAZL  Female              0     Yes        Yes
7041  8361-LTMKD    Male              1     Yes         No
7042  3186-AJIEK    Male              0      No         No

[7043 rows x 5 columns]

In [12]:
df_clientes.tail(10)

      customerID  gender  SeniorCitizen Partner Dependents
7033  9767-FFLEM    Male              0      No         No
7034  0639-TSIQW  Female              0      No         No
7035  8456-QDAVC    Male              0      No         No
7036  7750-EYXWZ  Female              0      No         No
7037  2569-WGERO  Female              0      No         No
7038  6840-RESVB    Male              0     Yes        Yes
7039  2234-XADUH  Female              0     Yes        Yes
7040  4801-JZAZL  Female              0     Yes        Yes
7041  8361-LTMKD    Male              1     Yes         No
7042  3186-AJIEK    Male              0      No         No

In [14]:
df_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   str
 1   gender         7043 non-null   str
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   str
 4   Dependents     7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 411.2 KB

In [15]:
df_clientes.describe()

       SeniorCitizen
count    7043.000000
mean        0.162147
std         0.368612
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000

In [16]:
df_servicos = pd.read_csv(r"C:\Users\User\OneDrive\Área de Trabalho\udemyPython\EDA\DADOS\churn_services.csv")
df_servicos

,customerID,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,Yes,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Yes,No,Fiber optic,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes
7039,2234-XADUH,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
7040,4801-JZAZL,No,No phone service,DSL,Yes,No,No,No,No,No
7041,8361-LTMKD,Yes,Yes,Fiber optic,No,No,No,No,No,No
7042,3186-AJIEK,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes

In [17]:
df_contratos = pd.read_csv(r"C:\Users\User\OneDrive\Área de Trabalho\udemyPython\EDA\DADOS\churn_contracts.csv")

In [18]:
df_contratos

,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...
7038,6840-RESVB,24,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,72,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,11,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,4,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,66,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [19]:
df_contratos.dtypes

customerID              str
tenure                int64
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [20]:
df_contratos["TotalCharges"]=df_contratos["TotalCharges"].astype(float)

ValueError: could not convert string to float: ' '

In [21]:
df_contratos["TotalCharges"]=pd.to_numeric(df_contratos["TotalCharges"],errors="coerce")

In [22]:
df_contratos.dtypes

customerID              str
tenure                int64
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
dtype: object

In [23]:
df_contratos.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   tenure            7043 non-null   int64
 2   Contract          7043 non-null   str
 3   PaperlessBilling  7043 non-null   str
 4   PaymentMethod     7043 non-null   str
 5   MonthlyCharges    7043 non-null   float64
 6   TotalCharges      7032 non-null   float64
 7   Churn             7043 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 748.0 KB

In [25]:
df_clientes=df_clientes.rename(columns={"SeniorCitizen":"ElderlyPerson"})

In [26]:
df_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   str
 1   gender         7043 non-null   str
 2   ElderlyPerson  7043 non-null   int64
 3   Partner        7043 non-null   str
 4   Dependents     7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 411.2 KB

In [27]:
df_clientes.rename(columns={"Partner":"Casado(a)"},inplace=True)

In [28]:
df_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   str
 1   gender         7043 non-null   str
 2   ElderlyPerson  7043 non-null   int64
 3   Casado(a)      7043 non-null   str
 4   Dependents     7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 411.2 KB

In [29]:
df_clientes.columns=["IDCliente","Genero","PessoaIdosa","Casado(a)","Dependentes"]

In [30]:
df_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   IDCliente    7043 non-null   str
 1   Genero       7043 non-null   str
 2   PessoaIdosa  7043 non-null   int64
 3   Casado(a)    7043 non-null   str
 4   Dependentes  7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 411.2 KB

In [33]:
df_servicos.rename(columns={"customerID":"IDCliente"}, inplace=True)

In [35]:
df_temp = df_clientes.merge(df_servicos, on=["IDCliente"])

In [37]:
df_temp.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   IDCliente         7043 non-null   str
 1   Genero            7043 non-null   str
 2   PessoaIdosa       7043 non-null   int64
 3   Casado(a)         7043 non-null   str
 4   Dependentes       7043 non-null   str
 5   PhoneService      7043 non-null   str
 6   MultipleLines     7043 non-null   str
 7   InternetService   7043 non-null   str
 8   OnlineSecurity    7043 non-null   str
 9   OnlineBackup      7043 non-null   str
 10  DeviceProtection  7043 non-null   str
 11  TechSupport       7043 non-null   str
 12  StreamingTV       7043 non-null   str
 13  StreamingMovies   7043 non-null   str
dtypes: int64(1), str(13)
memory usage: 1.2 MB

In [38]:
df_churn_temp=df_temp.merge(df_contratos,left_on=["IDCliente"],right_on=["customerID"])

In [39]:
df_churn_temp

,IDCliente,Genero,PessoaIdosa,Casado(a),Dependentes,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingTV,StreamingMovies,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,No,No phone service,DSL,No,Yes,...,No,No,7590-VHVEG,1,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,Yes,No,DSL,Yes,No,...,No,No,5575-GNVDE,34,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,Yes,No,DSL,Yes,Yes,...,No,No,3668-QPYBK,2,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,No,No phone service,DSL,Yes,No,...,No,No,7795-CFOCW,45,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,Yes,No,Fiber optic,No,No,...,No,No,9237-HQITU,2,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,Yes,Yes,DSL,Yes,No,...,Yes,Yes,6840-RESVB,24,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,Yes,Yes,Fiber optic,No,Yes,...,Yes,Yes,2234-XADUH,72,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,No,No phone service,DSL,Yes,No,...,No,No,4801-JZAZL,11,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,Yes,Yes,Fiber optic,No,No,...,No,No,8361-LTMKD,4,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,Yes,No,Fiber optic,Yes,No,...,Yes,Yes,3186-AJIEK,66,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [40]:
df_churn=df_clientes.merge(df_servicos, on=["IDCliente"]).merge(df_contratos,left_on=["IDCliente"],right_on=["customerID"])

In [42]:
df_churn.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   IDCliente         7043 non-null   str
 1   Genero            7043 non-null   str
 2   PessoaIdosa       7043 non-null   int64
 3   Casado(a)         7043 non-null   str
 4   Dependentes       7043 non-null   str
 5   PhoneService      7043 non-null   str
 6   MultipleLines     7043 non-null   str
 7   InternetService   7043 non-null   str
 8   OnlineSecurity    7043 non-null   str
 9   OnlineBackup      7043 non-null   str
 10  DeviceProtection  7043 non-null   str
 11  TechSupport       7043 non-null   str
 12  StreamingTV       7043 non-null   str
 13  StreamingMovies   7043 non-null   str
 14  customerID        7043 non-null   str
 15  tenure            7043 non-null   int64
 16  Contract          7043 non-null   str
 17  PaperlessBilling  7043 non-null   str
 18  PaymentMethod     7043 non-null   str
 19  MonthlyCharges    7043 non-null   float64
 20  TotalCharges      7032 non-null   float64
 21  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(18)
memory usage: 1.9 MB

In [44]:
df_churn.drop(["customerID"],inplace=True,axis=1)

In [45]:
df_churn.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   IDCliente         7043 non-null   str
 1   Genero            7043 non-null   str
 2   PessoaIdosa       7043 non-null   int64
 3   Casado(a)         7043 non-null   str
 4   Dependentes       7043 non-null   str
 5   PhoneService      7043 non-null   str
 6   MultipleLines     7043 non-null   str
 7   InternetService   7043 non-null   str
 8   OnlineSecurity    7043 non-null   str
 9   OnlineBackup      7043 non-null   str
 10  DeviceProtection  7043 non-null   str
 11  TechSupport       7043 non-null   str
 12  StreamingTV       7043 non-null   str
 13  StreamingMovies   7043 non-null   str
 14  tenure            7043 non-null   int64
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.8 MB

In [49]:
df_churn.isna().sum()

IDCliente            0
Genero               0
PessoaIdosa          0
Casado(a)            0
Dependentes          0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
tenure               0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [50]:
df_churn[df_churn.isna().any(axis=1)]

,IDCliente,Genero,PessoaIdosa,Casado(a),Dependentes,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,TechSupport,StreamingTV,StreamingMovies,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,No,No phone service,DSL,Yes,No,...,Yes,Yes,No,0,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,Yes,No,No,No internet service,No internet service,...,No internet service,No internet service,No internet service,0,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,Yes,No,DSL,Yes,Yes,...,No,Yes,Yes,0,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,Yes,Yes,No,No internet service,No internet service,...,No internet service,No internet service,No internet service,0,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,No,No phone service,DSL,Yes,Yes,...,Yes,Yes,No,0,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,Yes,No,No,No internet service,No internet service,...,No internet service,No internet service,No internet service,0,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,Yes,Yes,No,No internet service,No internet service,...,No internet service,No internet service,No internet service,0,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,Yes,No,No,No internet service,No internet service,...,No internet service,No internet service,No internet service,0,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,Yes,No,No,No internet service,No internet service,...,No internet service,No internet service,No internet service,0,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,Yes,Yes,DSL,No,Yes,...,Yes,Yes,No,0,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,Yes,Yes,DSL,Yes,Yes,...,Yes,No,No,0,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [51]:
df_churn.isna().any(axis=0).sum()

np.int64(1)