In [43]:
import pandas as pd

In [44]:
pd.__version__

'3.0.2'

In [45]:
dict_metrics = {"idade":[15,18,25,26,40,40,58,60],
                "altura":[160,165,149,172,174,174,178,168]}

In [46]:
type(dict_metrics)

dict

In [47]:
df=pd.DataFrame(dict_metrics)

In [48]:
type(df)

pandas.DataFrame

In [49]:
df

   idade  altura
0     15     160
1     18     165
2     25     149
3     26     172
4     40     174
5     40     174
6     58     178
7     60     168

In [50]:
print(f"Media de idade: {df['idade'].mean()}")
print(f'Media de altura: {df["altura"].mean()}')

Media de idade: 35.25
Media de altura: 167.5

In [51]:
print(f"Mediana de idade: {df['idade'].median()}")
print(f'Mediana de altura: {df["altura"].median()}')

Mediana de idade: 33.0
Mediana de altura: 170.0

In [52]:
print(f"Media de idade: {df['idade'].mean()}")
print(f'Media de altura: {df["altura"].mean()}')

Media de idade: 35.25
Media de altura: 167.5

In [53]:
print(f"Moda de idade: {df['idade'].mode()[0]}")
print(f'Moda de altura: {df["altura"].mode()}')

Moda de idade: 40
Moda de altura: 0    174
Name: altura, dtype: int64

In [54]:
print(f"Variancia de idade: {df['idade'].var()}")
print(f'Variencia de altura: {df["altura"].var()}')

Variancia de idade: 296.2142857142857
Variencia de altura: 88.57142857142857

In [55]:
print(f"Desvio padrao de idade: {df['idade'].std()}")
print(f'Desvio padrao de altura: {df["altura"].std()}')

Desvio padrao de idade: 17.210876959477854
Desvio padrao de altura: 9.411239481143202

In [56]:
df["idade"].std()  /  df["idade"].mean()  * 100

np.float64(48.82518286376696)

In [57]:
df["altura"].std()  /  df["altura"].mean()  * 100

np.float64(5.618650436503405)

In [58]:
df

   idade  altura
0     15     160
1     18     165
2     25     149
3     26     172
4     40     174
5     40     174
6     58     178
7     60     168

In [59]:
print(f"Simetria de idade: {df['idade'].skew()}")
print(f"Simetria de altura: {df['altura'].skew()}")

Simetria de idade: 0.44254516049230713
Simetria de altura: -1.1359101638062434

In [60]:
print(f"Curtose de idade: {df['idade'].kurtosis()}")
print(f"Curtose de altura: {df['altura'].kurtosis()}")

Curtose de idade: -1.3083027995345171
Curtose de altura: 1.064502601456815

In [61]:
df.describe()

           idade      altura
count   8.000000    8.000000
mean   35.250000  167.500000
std    17.210877    9.411239
min    15.000000  149.000000
25%    23.250000  163.750000
50%    33.000000  170.000000
75%    44.500000  174.000000
max    60.000000  178.000000