In [1]:
import pandas as pd

In [2]:
df=pd.read_json("dados/receitas.json", encoding='utf-8')
df

                                            Receitas
0  {'Titulo': 'Bolo de Chocolate', 'Tempo de Prep...
1  {'Titulo': 'Salada Caesar', 'Tempo de Preparo'...
2  {'Titulo': 'Pasta ao Pesto', 'Tempo de Preparo...

In [9]:
receita_expandidas = []
for receita in df['Receitas']:
    total_ingredientes = len(receita['Ingredientes'])
    receita_info = {
        'Titulo': receita['Titulo'],
        'Tempo de Preparo':receita["Tempo de Preparo"],
        'Porções':receita['Porcoes'],
        'Total de Ingredientes':total_ingredientes
    }
    receita_expandidas.append(receita_info)

In [10]:
receita_expandidas

[{'Titulo': 'Bolo de Chocolate',
  'Tempo de Preparo': '45 minutos',
  'Porções': 8,
  'Total de Ingredientes': 5},
 {'Titulo': 'Salada Caesar',
  'Tempo de Preparo': '20 minutos',
  'Porções': 4,
  'Total de Ingredientes': 4},
 {'Titulo': 'Pasta ao Pesto',
  'Tempo de Preparo': '30 minutos',
  'Porções': 2,
  'Total de Ingredientes': 5}]

In [11]:
df_expandido = pd.DataFrame(receita_expandidas)
df_expandido

              Titulo Tempo de Preparo  Porções  Total de Ingredientes
0  Bolo de Chocolate       45 minutos        8                      5
1      Salada Caesar       20 minutos        4                      4
2     Pasta ao Pesto       30 minutos        2                      5