In [4]:
import pandas as pd

In [7]:
dados={
    'Times':['Flamengo','Palmeiras','São Paulo','Santos','Corinthians'],
    'Partidas_Jogadas':[10,10,10,10,10,],
    'Vitorias':[7,5,6,4,3],
    'Empates':[2,3,1,3,2],
    'Derrotas':[1,2,3,3,5],
    'Gols_Pro':[22,18,16,14,10],
    'Gols_contra':[10,12,15,16,20]
    }

In [8]:
df=pd.DataFrame(dados)
df

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_contra
0,Flamengo,10,7,2,1,22,10
1,Palmeiras,10,5,3,2,18,12
2,São Paulo,10,6,1,3,16,15
3,Santos,10,4,3,3,14,16
4,Corinthians,10,3,2,5,10,20

In [11]:
df['Saldos_Gols']=  df['Gols_Pro']- df['Gols_contra']
df

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_contra,Saldos_Gols
0,Flamengo,10,7,2,1,22,10,12
1,Palmeiras,10,5,3,2,18,12,6
2,São Paulo,10,6,1,3,16,15,1
3,Santos,10,4,3,3,14,16,-2
4,Corinthians,10,3,2,5,10,20,-10

In [12]:
df['Pontos']=df['Vitorias']*3 + df['Empates']*1
df

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_contra,Saldos_Gols,Pontos
0,Flamengo,10,7,2,1,22,10,12,23
1,Palmeiras,10,5,3,2,18,12,6,18
2,São Paulo,10,6,1,3,16,15,1,19
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,20,-10,11

In [14]:
df = df.sort_values(by='Pontos',ascending=False)
df

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_contra,Saldos_Gols,Pontos
0,Flamengo,10,7,2,1,22,10,12,23
2,São Paulo,10,6,1,3,16,15,1,19
1,Palmeiras,10,5,3,2,18,12,6,18
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,20,-10,11

In [17]:
df.to_excel("dados/campeonato_futebol.xlsx", index=False)