In [1]:
import pandas as pd

In [4]:
dados  = {
    'Nome':['Alice','Bob','Charli'],
    'Idade':[24,38,22],
    'Cidade':['São Paulo','Rio de Jnaneiro','Belo Horizonte']
}

In [5]:
df = pd.DataFrame(dados)
df

     Nome  Idade           Cidade
0   Alice     24        São Paulo
1     Bob     38  Rio de Jnaneiro
2  Charli     22   Belo Horizonte

In [6]:
df.head(1)

    Nome  Idade     Cidade
0  Alice     24  São Paulo

In [7]:
df.tail(1)

     Nome  Idade          Cidade
2  Charli     22  Belo Horizonte

In [8]:
dados_notas = {
    'Nome':['Alice','Bob','Charli','David','Eva'],
    'Matematica': [85,90,78,88,92],
    'Fisica': [80,75,88,85,95],
    'Quimica':[78,82,85,80,88]
}

In [10]:
df_notas=pd.DataFrame(dados_notas)
df_notas

     Nome  Matematica  Fisica  Quimica
0   Alice          85      80       78
1     Bob          90      75       82
2  Charli          78      88       85
3   David          88      85       80
4     Eva          92      95       88

In [11]:
df_notas['Media']= df_notas[['Matematica','Fisica','Quimica']].mean(axis=1)
df_notas

     Nome  Matematica  Fisica  Quimica      Media
0   Alice          85      80       78  81.000000
1     Bob          90      75       82  82.333333
2  Charli          78      88       85  83.666667
3   David          88      85       80  84.333333
4     Eva          92      95       88  91.666667

In [13]:
aluno_aprovado =df_notas[df_notas['Media']>=82.5]
aluno_aprovado

     Nome  Matematica  Fisica  Quimica      Media
2  Charli          78      88       85  83.666667
3   David          88      85       80  84.333333
4     Eva          92      95       88  91.666667

In [15]:
df_notas[['Nome','Media']]

     Nome      Media
0   Alice  81.000000
1     Bob  82.333333
2  Charli  83.666667
3   David  84.333333
4     Eva  91.666667

In [16]:
aluno_aprovado[['Nome','Media']]

     Nome      Media
2  Charli  83.666667
3   David  84.333333
4     Eva  91.666667