In [1]:
import pandas as pd

In [2]:
df=pd.read_json("dados/receitas.json", encoding="utf-8")
df

                                            Receitas
0  {'Titulo': 'Bolo de Chocolate', 'Tempo de Prep...
1  {'Titulo': 'Salada Caesar', 'Tempo de Preparo'...
2  {'Titulo': 'Pasta ao Pesto', 'Tempo de Preparo...

In [3]:
df_receitas=pd.json_normalize(
    df['Receitas'],
    'Ingredientes',
    ['Titulo','Tempo de Preparo','Porcoes']
)

In [4]:
df_receitas

         Ingrediente   quantidade             Titulo Tempo de Preparo Porcoes
0   Farinha de Trigo    2 xicaras  Bolo de Chocolate       45 minutos       8
0             Açucar    1 xicaras  Bolo de Chocolate       45 minutos       8
0               Ovos    3 xicaras  Bolo de Chocolate       45 minutos       8
0              Leite    1 xicaras  Bolo de Chocolate       45 minutos       8
0           Manteiga  1/2 xicaras  Bolo de Chocolate       45 minutos       8
1      Alface Romana     2 cabeça      Salada Caesar       20 minutos       4
1           Croutons    1 xicaras      Salada Caesar       20 minutos       4
1    Queijo Parmesão  1/2 xicaras      Salada Caesar       20 minutos       4
1       Molho Caesar  1/4 xicaras      Salada Caesar       20 minutos       4
2              Massa         200g     Pasta ao Pesto       30 minutos       2
2  Manjericão Fresco  1/2 xicaras     Pasta ao Pesto       30 minutos       2
2    Azeite de Oliva  1/3 xicaras     Pasta ao Pesto       30 minutos       2
2              Nozes  1/4 xicaras     Pasta ao Pesto       30 minutos       2
2    Queijo Parmesão  1/4 xicaras     Pasta ao Pesto       30 minutos       2

In [9]:
colunas_ordenadas = ['Titulo', 'Tempo de Preparo', 'Porcoes', 'Ingrediente', 'quantidade']

# Reordenando o DataFrame
df_receitas = df_receitas[colunas_ordenadas]

df_receitas

              Titulo Tempo de Preparo Porcoes        Ingrediente   quantidade
0  Bolo de Chocolate       45 minutos       8   Farinha de Trigo    2 xicaras
0  Bolo de Chocolate       45 minutos       8             Açucar    1 xicaras
0  Bolo de Chocolate       45 minutos       8               Ovos    3 xicaras
0  Bolo de Chocolate       45 minutos       8              Leite    1 xicaras
0  Bolo de Chocolate       45 minutos       8           Manteiga  1/2 xicaras
1      Salada Caesar       20 minutos       4      Alface Romana     2 cabeça
1      Salada Caesar       20 minutos       4           Croutons    1 xicaras
1      Salada Caesar       20 minutos       4    Queijo Parmesão  1/2 xicaras
1      Salada Caesar       20 minutos       4       Molho Caesar  1/4 xicaras
2     Pasta ao Pesto       30 minutos       2              Massa         200g
2     Pasta ao Pesto       30 minutos       2  Manjericão Fresco  1/2 xicaras
2     Pasta ao Pesto       30 minutos       2    Azeite de Oliva  1/3 xicaras
2     Pasta ao Pesto       30 minutos       2              Nozes  1/4 xicaras
2     Pasta ao Pesto       30 minutos       2    Queijo Parmesão  1/4 xicaras